pipeline {
    agent {
        docker {
            image 'maven:3.5.3-jdk-10-slim'
            args '-e deployEnv=dops'
            alwaysPull true
        }
    }
    stages {
        stage('Docker_commands') {
            steps {
                sh 'echo $deployEnv'
            }
        }
    }
}