pipeline{
    agent{
        docker {
            image 'maven:3.5.3-jdk-10-slim'
        }
    }
    stages{
        stage('Docker-commands-test') {
            steps{
                sh 'mvn -v'
            }
        }
    }
}