pipeline {
    agent {
        docker {
            image 'maven:3.5.3-jdk-10-slim'
            args '-e deployEnv=dops'
            alwaysPull true
            customworkspace '/var/lib/jenkins/customWorkspace'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo $deployEnv'
            }
        }
    }
}